const branchListString = [
    "Tất cả",
    "Vinh",
    "Hà Tĩnh",
    "Đông Hà",
    "Huế",
    "Đà Nẵng",
    "Hội An",
    "Tam Kỳ",
    "Quảng Ngãi",
    "Quy Nhơn",
    "Tuy Hòa",
    "Nha Trang",
    "Phan Rang",
    "Phan Thiết",
    "Đà Lạt",
    "Đức Trọng",
    "Di Linh",
    "Bảo Lộc",
    "Biên Hòa",
    "Trảng Bom",
    "Long Khánh",
    "Long Thành",
    "Bà Rịa", 
    "Vũng Tàu",
    "Dĩ An",
    "Thuận An",
    "Bình Dương",
    "Bến Cát",
    "Bình Phước",
    "Hóc Môn",
    "Tây Ninh",
    "Trảng Bàng",
    "Long An",
    "Bến Lức",
    "Mỹ Tho",
    "Gò Công",
    "Cai Lậy",
    "Bến Tre",
    "Trà Vinh",
    "Vĩnh Long",
    "Sa Đéc",
    "Cao Lãnh",
    "Hồng Ngự",
    "Cần Thơ",
    "Thốt Nốt",
    "Châu Đốc",
    "Châu Phú",
    "Tri Tôn",
    "Long Xuyên",
    "Hà Tiên",
    "Rạch Giá",
    "Sóc Trăng",
    "Vĩnh Châu",
    "Ngã Năm", 
    "Ngã Bảy",
    "Vị Thanh",
    "Bạc Liêu",
    "Cà Mau" 
  ]

  export default branchListString